apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: webapp
spec:
  forProvider:
    region: us-east-1
    imageTagMutability: MUTABLE
    imageScanningConfiguration:
      - scanOnPush: true
    forceDelete: true
  providerConfigRef:
    name: aws-config

---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: apprunner-ecr-role
  labels:
    role: apprunner-ecr-role
spec:
  forProvider:
    description: "Role for App Runner to access ECR"
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": "build.apprunner.amazonaws.com"
            }
          }
        ]
      }
  providerConfigRef:
    name: aws-config

---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: apprunner-ecr-policy-attachment
spec:
  forProvider:
    policyArn: "arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess"
    roleRef:
      name: apprunner-ecr-role
  providerConfigRef:
    name: aws-config

---
apiVersion: apprunner.aws.upbound.io/v1beta1
kind: Service
metadata:
  name: webapp-service
spec:
  forProvider:
    region: us-east-1
    serviceName: webapp-service_faizun
    sourceConfiguration:
      - authenticationConfiguration:
          - accessRoleArn: arn:aws:iam::192626564093:role/apprunner-ecr-role

        imageRepository:
          - imageIdentifier: "192626564093.dkr.ecr.us-east-1.amazonaws.com/webapp:latest" # Placeholder until first push, or user updates
            imageRepositoryType: "ECR"
            imageConfiguration:
              - port: "8080"
  providerConfigRef:
    name: aws-config
